[book]
authors = ["Moon-of-Noon"]
language = "zh-CN"
src = ""
title = "Witchgci"
site-url = "/witchgci/"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/Moon-of-Noon/witchgci"

[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 10

[preprocessor.chapter-list]
